import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './styles.css';


import { QueryProvader } from './queryProvader';

import Providers from './Providers';


const roboto = Roboto({weight:'400', subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Providers>
      <QueryProvader>
        
          {children}
        
          </QueryProvader>
          </Providers>
          </body>
    </html>
  )
}
